version: '3.7'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP Bolt port
      - "7687:7687"  # Bolt protocol port
    environment:
      NEO4J_AUTH: neo4j/teste123  # Usuário e senha padrão
